### ISSUE TITLE
'ModuleNotFoundError: No module named 'assistants.package'.

### ISSUE THREAD

**Issue by selfishark** [JarodMica/Vivy#12]
**Describe the Issue**
Hi Jarod, thank you so much for the current updates and bug fixes; I cloned the repo with the recent updates and tried to execute a test.py and an assistantp.py from my Visual Studio and faced a package error saying 'ModuleNotFoundError: No module named 'assistants.package'.

I tried:  `pip install assistants` in the command prompt after inserting the line `from assistants.package.assistant_utils import *`

So, how can I fix it, please? 
Best,

![image](https://user-images.githubusercontent.com/105219120/235380936-f9a38716-68c0-48f2-aa47-e84decf4e454.png)

**Comment by JarodMica** [comment]
In the most recent updates I moved some functions and files around so I would recommend recloning the latest repository and going from there.  In your case, it's not a matter of pip install as I haven't designed my repo to be installable, rather file and folder structure.

Once you clone the repo, the only location you should be making any python scripts inside of should be the assistants folder so path structure should be like this [path to folder]/Vivy/assistants/[your python script here]

Based on what I see though, I think you can resolve it by doing 
```from .assistant_utils import *```
