### ISSUE TITLE
Code Run Stuck @Initiated

### ISSUE THREAD

**Issue by mastershifu-dev** [JarodMica/Vivy#15]
While I am trying to run the code on VS Code, it got stucked while initiating. Is there any problem with my settings?
![image](https://github.com/JarodMica/Vivy/assets/27801509/1c3c1266-923b-442d-8c7e-b4c6a69227d1)
Here is a screenshot of my problem.

**Comment by JarodMica** [comment]
I believe this is the intended behavior of this version, but the master branch is months ahead of the tortoise branch which I'll merge into master soon.
