### ISSUE TITLE
AttributeError: 'ElevenLabsVoice' object has no attribute 'generate_and_play_audio'

### ISSUE THREAD

**Issue by technomarshal** [JarodMica/Vivy#16]
**Describe the bug**
When enabling ElevenLabs voices upon reply from the AI the code in kokoro.py shows an attribute error

**To Reproduce**
1. Enable ElevenLabs in tsest.py script
2. Start debugging
3. Once application is running speak key word ("hello" in my case)
4. Reply in terminal shows : Listening: DOne listening. Google heard: hello Keyword heard
5. Then see the Exception has occurred in the kokoro.py file, line 110  self.voice.generate_and_play_audio(f"{response}", playInBackground=False)

**Expected behavior**
I expected the application to interface with teh ElevenLabs API and playback the ChatGPT reply using the voice noted in the test.py script. I have the voice name set to "Rachel"

**Screenshots**
![image](https://github.com/JarodMica/Vivy/assets/22423773/181e14db-60fb-4769-83fe-df1c81236b5e)

**Desktop (please complete the following information):**
 - OS: Win 11

**Additional context**
No other issues, if I disable ElevenLabs, I get the application to work with the default voice in Windows.

**Comment by JarodMica** [comment]
It looks like the author renamed the function... So I'll have to update it. When I get the time, I'll do it or you could PR it if you want as well!

**Comment by technomarshal** [comment]
Hey Jarod!

Thanks for the feedback. I did some digging in the ElevenLabsVoice.py and found that the syntax just needs to drop the 'and', so it should read: generate_play_audio the updated block looks like this:

def generate_voice(self, response, useEL):
        if useEL == True:
            self.voice.generate_play_audio(f"{response}", playInBackground=False)
        else:
            self.engine.say(f"{response}")
            self.engine.runAndWait()

It does have a note in the ElevenLabsVoice.py though that the generate_play_audio function is deprecated and to use generate_play_audio_v2() instead. For now, though the updated function syntax is working, 

I see in here there is a stream function too, I might have to play with that too and see how much faster responses are.

**Comment by JarodMica** [comment]
I didn't want to make any modifications to the program, so I froze the requirements in this commit here: https://github.com/JarodMica/Vivy/commit/da55b994d8f5bbc18b2df1bcb313427382e1fcd3

Streaming may be faster to go with later on though!
