### ISSUE TITLE
I got problem in assistant.py

### ISSUE THREAD

**Issue by KshitizMagarok** [JarodMica/Vivy#3]
**Describe the Issue**
No API Key set for Eleven Labs
Initiated: 

**To Reproduce**

**Expected behavior**
No API Key set for Eleven Labs
Initiated: 

 #**Screenshots*
![Screenshot (1)](https://user-images.githubusercontent.com/130017615/230601861-3869736f-4e2d-43da-87be-add2726c9357.png)
![Screenshot (2)](https://user-images.githubusercontent.com/130017615/230601866-da1bf096-4d87-46ce-8c7f-edd420565d2d.png)
![Screenshot (3)](https://user-images.githubusercontent.com/130017615/230601869-b34b59db-336b-4510-8e68-9962a68e2b4f.png)
![Screenshot (4)](https://user-images.githubusercontent.com/130017615/230601872-35926d8a-c84a-4c58-849d-4f23a774df02.png)
*
.

**Desktop (please complete the following information):**
  Windows 11),
**Additional context**
I got problem like 

No API Key set for Eleven Labs
Initiated: 
![Screenshot (4)](https://user-images.githubusercontent.com/130017615/230602141-c520839b-f6ad-46b4-82f1-7cf62c8d74de.png)

**Comment by JarodMica** [comment]
The code is running fine, but you don't have an Eleven Labs key set. Use the keys template that's in the assistants folder, rename the file appropriately, and enter your keys in appropriately.

**Comment by KshitizMagarok** [comment]
what are you trying to say i am not understanding sry

**Comment by KshitizMagarok** [comment]
hello sir i am not getting respond from your py files
when i run by f5
it shows only 
ERROR:root:RESPONSE DATA: {"detail":{"status":"invalid_api_key","message":"Invalid API key: 'assistant'"}}
ERROR:root:REQUEST THAT CAUSED THE ERROR:
-----------START-----------
accept: */*
Connection: keep-alive
xi-api-key: assistant

None
No API Key set for Eleven Labs
Initiated:
[`[](url)`](url)
![Screenshot (9)](https://user-images.githubusercontent.com/130017615/230625734-b2a81585-7f76-4c71-8b3e-e53a403486d1.png)
![Screenshot (8)](https://user-images.githubusercontent.com/130017615/230625748-0e01d945-6ef4-4063-9f8f-17805dac8f6f.png)
 


can you give me answer by showing your screen in next comment plz help me

**Comment by JarodMica** [comment]
KshitizMagarok, are there any instructions that were unclear in the YouTube video? The YouTube video is me showing my screen the entire time.  

Sorry, I'm having a hard time understanding what your trying to say other than you are trying to run my python files and they're not working. 

Based on this latest image, your issue comes from the fast your EL_Key is not from eleven labs. You need to get an Eleven labs API key from their website

**Comment by ainzlpnoresponse** [comment]
@JarodMica Thanks for your project! But I'm afraid I have the same issue after written the EL_KEY in keys.txt part like this:
![image](https://user-images.githubusercontent.com/58736786/230740311-f8447410-01f9-42c4-8bbd-507e5a935693.png)
but execution doesnt work properly catching my EL api:
![image](https://user-images.githubusercontent.com/58736786/230740320-f1b6dd3f-80b0-4e1c-b417-7bc0ca27a836.png)
I'm using windows10 , is it related to free api usage?

**Comment by JarodMica** [comment]
> @JarodMica Thanks for your project! But I'm afraid I have the same issue after written the EL_KEY in keys.txt part like this: ![image](https://user-images.githubusercontent.com/58736786/230740311-f8447410-01f9-42c4-8bbd-507e5a935693.png) but execution doesnt work properly catching my EL api: ![image](https://user-images.githubusercontent.com/58736786/230740320-f1b6dd3f-80b0-4e1c-b417-7bc0ca27a836.png) I'm using windows10 , is it related to free api usage?

I believe you're API key is working fine, but the name of your Eleven Labs voice might be incorrect.  If you trained a voice for vivy, it might actually be "Vivy" with a capitalized "V" as eleven labs is cases sensitve when pulling names.  I am making a second release today that updates this logic to default to Eleven Labs "Rachel if there is some type of typo or it's not finding the voice
