### ISSUE TITLE
Can you help me plz read comment and give a code of his plzzzz

### ISSUE THREAD

**Issue by KshitizMagarok** [JarodMica/Vivy#5]
**Describe the Issue**
I want to change voice in any natural language.  when i i said to change voice in  hindi natural girl voice.

, Windows 11 
*Additional context
i wan to change voice of this ai assistant voice and  also give her a features to translate language

**Comment by JarodMica** [comment]
At the current moment, my model is built to only support English at the moment, so you would have to modify it to be able to support another language. 

That being said, you've been commenting on a lot of my stuff and I appreciate the enthusiasm, however, I don't have the time to personally guide anyone through all of my code. If you have any specific questions about the project, specific issues, or feature request, I'll respond as I go.  My advice is if you have questions, use ChatGPT to guide you as I have been using it to as well.
