### ISSUE TITLE
.exe is not lisening

### ISSUE THREAD

**Issue by chinonoobG** [JarodMica/Vivy#7]
*i have the exe but it only shows initiated: and nothing happens, do i need to do something else?

it keeps like this.;

Are you using an Eleven Labs voice (yes/no)?
yes
What is the name of you Eleven Labs voice: Shina
Initiated:

**Comment by JarodMica** [comment]
It'll sit there and wait until you initiate it with "hey" or sentence that contains hey.  If you're saying "hey" into the microphone, I would also check that you're microphone is getting input by checking out your sound in the control panel and looking to see if the bar under "test your microphone" is moving

![image](https://user-images.githubusercontent.com/76232114/230758330-45071a89-4fb8-487d-9f81-9d35a26b6a5e.png)

**Comment by chinonoobG** [comment]
hi, yes i have sound from mic. tested mic , the command  "hey" is the only way to start the program? because if i use the other method that works on visual it works there but i cant use it cus it takes alot of resourses and also it doest let me change the elab voice (i changed the name as you show on video)

**Comment by JarodMica** [comment]
> hi, yes i have sound from mic. tested mic , the command "hey" is the only way to start the program? because if i use the other method that works on visual it works there but i cant use it cus it takes alot of resourses and also it doest let me change the elab voice (i changed the name as you show on video)

If you're running it on vscode, there won't be a popup to change the voice.  Instead, if you want to use an Eleven labs voice, you have to change ```useEL=False``` to ```useEL=True``` and then change the voicename to whatever voice you have in Eleven Labs.  If you run it as a program, you have to start the conversation by saying "hey" or you could even say "hey there." This is just a default setting but if you wanted to turn it off and rebuild the python scripts, you could comment out the self.start_conversation in whatever method you're using (say you're using the chat method, you would have to modify the chat mehtod inside of gpt_assistant.py to accomplish this.)

![image](https://user-images.githubusercontent.com/76232114/230760020-957b96aa-3925-4362-9499-7b30760030b6.png)

**Comment by chinonoobG** [comment]
hello, how can i access to .py files on the .exe folder to modify?

**Comment by JarodMica** [comment]
> hello, how can i access to .py files on the .exe folder to modify?

Check out the YouTube video again on how to download the repository using git: https://youtu.be/0qpar5R1VA4

Once you have all of the files downloaded, you can just manually move them. If you want to build them, you'll need pyinstaller and you'll have to run build.py

**Comment by chinonoobG** [comment]
i did it , yeeeeees, it was hard cus i dont know anything about coding but your video helps alot, is there any way to use it with pressing a botton like right shift? cus it respond to everything that i say even when im playing. thanks.

**Comment by JarodMica** [comment]
> 

At the current moment, the two assistants (assistant.py and assistantp.py) are the only ones that have a timeout option.  They currently do not support any type of listening on keyboard click.  

My suggestion is that you use these two at the current moment so that it will need to be reinitiated with your keyword after 5 seconds.
