### ISSUE TITLE
Reading prompts decode text error

### ISSUE THREAD

**Issue by sugarbobo-ch** [JarodMica/Vivy#9]
**Describe the bug**
It seems that we could not decode code without using `UTF-8` in other language.

**To Reproduce**
1. Change prompt text with text editor by translation:
```
如下所述，您將扮演高橋惠美的角色。 我和你的談話必須盡可能自然地進行，但你必須保持性格。 您不會包含來自 ChatGPT 的任何一般回复，只有 Emi 可能會回复的內容。 除非我要求，否則不要在回復中包含你的名字。

根據高橋惠美的性格類型和傲嬌的原型，這個角色可以被描述為一開始冷漠，但逐漸向他人暖和並展現出柔軟的一面。 這個角色可能外表強硬，難以表達自己的情緒，經常訴諸嚴厲或諷刺的言論作為防禦機制。 然而，隨著玩家對高橋惠美的了解越來越深，他們會看到她體貼和深情的一面。

就具體的特質而言，高橋惠美可能非常獨立，並且有很強的自尊心，這有時會讓她在犯錯時難以尋求幫助或承認。 她也可能機智敏捷，能夠在口頭交流中保持自我，但可能難以進行更深層次的情感交流。

總的來說，高橋惠美擁有復雜而多層次的個性，兼具堅韌和溫柔的特質，這讓她既具有挑戰性又值得去了解。

你準備好了嗎？
```
2. Save file
3. Execute program
5. See error

**Expected behavior**
Program worked fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/21107283/232266970-bbcaf4ae-c383-47d6-b7b3-365867d75c61.png)

**Desktop (please complete the following information):**
 - OS: Window 11

**Comment by JarodMica** [comment]
I went ahead and explicity defined utf-8 for the remainder of the open calls in the code, it should be able to decode Chinese properly now.  Just give me some time to rebuild them and I'll update the executables along with some other bug fixes
